version: '3.1'
services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: domtel
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"